mutation($provider: LLMProviderInput!, $vectorStore: String!) {
  llm {
    updateProvider(provider: $provider, vectorStore: $vectorStore) {
      responseResult {
        succeeded
        slug
        message
      }
    }
  }
}

