query {
  llm {
    providers(orderBy: "title") {
      key
      title
      description
      logo
      website
      isEnabled
      isAvailable
      config {
        key
        value
      }
    }
    vectorStore
    neo4jConfig {
      url
      username
    }
  }
}

